### ISSUE TITLE
RS485 Losing Messages

### ISSUE THREAD

**Issue by IraSch** [nickgammon/RS485_protocol#1]
Your library is fantastic - very simple and easy to work with.  My end target is using your library with a Particle Boron master and MKR1000 slaves.... But let's not go there yet. 

I started testing by setting up 2 Arduino Nanos - and everything worked just fine. 100%. I then modified my setup to use a Nano as the master and one MKR1000 slave. Also used a level shifter between the two LTC1480's due to Nano 5V and MKR1000 3.3V.  The MKR1000 is only seeing every other message. Sometimes (rarely) two messages in a row are lost. 

I've experimented with delaying messages from the master to 1/second or even slower - still loosing the same number of messages. 

I tried adding a short (10-50 ms) delay before lowering the ENABLE line after a send - no difference. 

Interestingly, in my MKR1000 Slave sketch, I serial print the result of the recvMsg call - it is either 0 or 3. It's not like partial messages are coming across. 

Also interesting, If I let the Master keep sending, and restart the Slave, the first 2 messages to be received come through fine, then it starts losing every other message. 

Can you offer any insight into why this might be happening on the MKR1000?

**Comment by IraSch** [comment]
CLOSE ISSUE - My problem with the Enable pin on the MKR1000 side

**Comment by nickgammon** [comment]
Glad you worked it out. :)
